---
# Default values for caddy role
# Provide templates and files from the consuming project.

# Optional variables with sensible defaults
caddy_caddyfile_template: Caddyfile.default.j2
caddy_local_docker_command: >-
  {{ 'docker' if lookup('ansible.builtin.pipe', 'uname -s') == 'Darwin'
     else 'sudo docker' }}
